### ISSUE TITLE
Creating a catalog without saving left an empty catalog in the list

### ISSUE THREAD

**Issue by cecton** [tenforce/webcat#2]
When you try to create a new catalog but don't save it, if you leave the page by clicking on "catalogs" again (to get the list of available catalogs), you will see an empty "ghost" catalog has been created. If you refresh the page, it's gone.

@erikap confirmed it's a bug

**Comment by madnificent** [comment]
Can you give me a pull request?

You may want to look at http://emberjs.com/api/data/classes/DS.Model.html#property_isNew to filter the catalogs by.  The same issue will be apparent in the other views.

Alternatively, we can show the record, whilst indicating it is new and/or dirty.
